### ISSUE TITLE
Accessing Cell X Genes Files Without MAGIC Smooth

### ISSUE THREAD

**Issue by bhonick** [hubmapconsortium/use-case-library#12]
A user submitted the following inquiry to the HuBMAP Helpdesk:

> I think that for the atac seq data (like https://portal.hubmapconsortium.org/browse/dataset/d2a5974f9fbc2d489970b199ee007578 https://portal.hubmapconsortium.org/browse/dataset/d2a5974f9fbc2d489970b199ee007578 ), I can only access cell x bin and cell x gene files, for the later file (cell x gene), the matrix is smoothed by magic. This is a quite large file, and I wonder if I can access the cell x genes file without magic smooth or not. Since the file has been changed to cell x bin, it will be quite hard for me to use Seurat to calculate the gene activity score again.

The following tags are applicable:
Explore HuBMAP Data
Experimental Biologist
Computational Biologist
Clinician
Data Contributor
Educator
Student

**Comment by tsliaw** [comment]
This is now captured as a user request in the internal HIVE-HMS Jira as this does not reflect a high level use case and more of a user request.
